name: publish

on:
  push:
    branches: [master]
    paths: ['package.json']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  publish-on-npm:
    runs-on: ubuntu-latest
    # don't publish on tag creation (assume that package was already published during committing to master branch)
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/') || github.event_type == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: 12 }
      # create cache for node modules
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: node-12-modules-${{ hashFiles('**/yarn.lock') }}
      # call yarn install if no cache was found
      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      # publish package
      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
          access: 'public'
      # log results
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
